### ISSUE TITLE
ValueError: API token not defined

### ISSUE THREAD

**Issue by MuriloIuryBarbosa** [dwave-examples/3d-bin-packing#36]
Olá, podem me ajudar com esse erro?

**Comment by JoelPasvolsky** [comment]
Hi @MuriloIuryBarbosa, 

Are you working in [Leap's IDE](https://www.dwavesys.com/solutions-and-products/cloud-platform/) or did you clone the repo to run locally on your computer?

- If you're running the example locally, see the [configuring access](https://docs.ocean.dwavesys.com/en/stable/overview/sapi.html) documentation
- If you're running the example in the Leap IDE, take a look at [Finding a Workspace’s API Token](https://docs.dwavesys.com/docs/latest/ide_user_workspaces.html#finding-a-workspace-s-api-token) and the following sections in that document
